runtime: python39
instance_class: F1

env_variables:
  GOOGLE_CLOUD_PROJECT: "tarannumandarif786"
  BUCKET_NAME: "photo-directory-ta786"

handlers:
# General static files
- url: /static
  static_dir: static
  secure: always
  http_headers:
    X-Frame-Options: DENY
    X-Content-Type-Options: nosniff
    Strict-Transport-Security: max-age=31536000; includeSubDomains
    X-XSS-Protection: 1; mode=block

- url: /.*
  script: auto
  secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
  max_concurrent_requests: 50
  target_throughput_utilization: 0.6
  min_pending_latency: 30ms
  max_pending_latency: automatic

entrypoint: gunicorn -b :$PORT -w 2 --timeout 300 --keep-alive 300 --max-requests 1000 --max-requests-jitter 50 app:app

readiness_check:
  app_start_timeout_sec: 300

liveness_check:
  initial_delay_sec: 300 